---
name: JavaScript-Minifier-XS
version: 0.06
author:
  - Graham TerMarsch (cpan@howlingfrog.com)
abstract: XS based JavaScript minifier
license: perl
resources:
  license: ~
requires:
  perl: 5.006
build_requires:
  Test::More: 0
provides:
  JavaScript::Minifier::XS:
    file: lib/JavaScript/Minifier/XS.pm
    version: 0.06
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
