---
name: JavaScript-Minifier-XS
version: 0.05
author:
  - "Graham TerMarsch (cpan@howlingfrog.com)"
abstract: XS based JavaScript minifier
license: perl
requires:
  perl: 5.006
build_requires:
  Test::More: 0
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  JavaScript::Minifier::XS:
    file: lib/JavaScript/Minifier/XS.pm
    version: 0.05
resources:
  license: http://dev.perl.org/licenses/
