---
abstract: 'XS based JavaScript minifier'
author:
  - 'Graham TerMarsch (cpan@howlingfrog.com)'
build_requires:
  ExtUtils::CBuilder: '0'
  Test::More: '0'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4206, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JavaScript-Minifier-XS
provides:
  JavaScript::Minifier::XS:
    file: lib/JavaScript/Minifier/XS.pm
    version: '0.11'
requires:
  perl: v5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: '0.11'
